version: "3.8"
   
services:
  db:
    restart: always
    image: postgres:14
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - DATABASE_NAME=alocai
      - DATABASE_USER=alocai
      - DATABASE_PASSWORD=alocai
      - DATABASE_HOST=db
  web:
    restart: always
    build: .
    command: bash -c "pytest && python manage.py makemigrations &&  python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=alocai
      - DATABASE_USER=alocai
      - DATABASE_PASSWORD=alocai
      - DATABASE_HOST=db
    depends_on:
      - db
