# Generated by Django 3.1.3 on 2022-01-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='space',
            field=models.IntegerField(),
        ),
    ]
